In [9]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
for i in a:
    print(i*i)

0
1
4
9
16
25
36
49
64
81


In [3]:
b = [i *i for i in a]
b

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [4]:
c = [i*i for i in a if i%2 == 1]
c

[1, 9, 25, 49, 81]

In [12]:
# a = ['Orange', 'apple', 'banana']
d = [i*i for i in a if i %2 == 1]

In [13]:
d

[1, 9, 25, 49, 81]

In [14]:
# Dictionary Comprehensions

In [16]:
a = list(range(10))
b = list(range(10,20))
c = dict()

d = {key:value for (key, value) in zip(a,b)}
d

{0: 10, 1: 11, 2: 12, 3: 13, 4: 14, 5: 15, 6: 16, 7: 17, 8: 18, 9: 19}

In [17]:
e = {key:value for (key, value) in d.items() if value> 15 }

In [18]:
e

{6: 16, 7: 17, 8: 18, 9: 19}

In [19]:
a = set(range(10))
a

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [20]:
b = {i for i in a if i > 6}

In [21]:
b

{7, 8, 9}

In [ ]:
# Numpy & Pandas

In [22]:
! conda list

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  2019.10                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_0  
anaconda-project          0.8.3                      py_0  
appdirs                   1.4.4                    pypi_0    pypi
asgiref                   3.2.10                   pypi_0    pypi
asn1crypto                1.0.1                    py37_0  
astroid                   2.3.1                    py37_0  
astropy                   3.2.1            py37he774522_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.2.0                     py_0  
babel                     2.7.0                      py_0  
backcall                

WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename C:\ProgramData\Anaconda3\conda-meta\tornado-6.0.3-py37he774522_0.json.  Please remove this file manually (you may need to reboot to free file handles)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename C:\ProgramData\Anaconda3\conda-meta\matplotlib-3.1.1-py37hc8f65d3_0.json.  Please remove this file manually (you may need to reboot to free file handles)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename C:\ProgramData\Anaconda3\conda-meta\pip-19.2.3-py37_0.json.  Please remove this file manually (you may need to reboot to free file handles)


In [ ]:
! pip install numpy

In [ ]:
! pip upgrade numpy

In [23]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [24]:
10/3

3.3333333333333335

In [25]:
numpy.ceil(10/3)

4.0

In [26]:
import numpy as np

In [38]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [28]:
a.ndim

1

In [40]:
a.shape

(3,)

In [41]:
a.size

3

In [42]:
a = np.array([[1,2,3], [2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [30]:
a.ndim

2

In [43]:
a.shape

(2, 3)

In [44]:
a.size

6

In [45]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b = np.arange(4, 10)
b

array([4, 5, 6, 7, 8, 9])

In [47]:
b = np.arange(2,10, 2)
b

array([2, 4, 6, 8])

In [53]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [71]:
np.random.seed(0)

b = np.random.sample(3)
b

array([0.5488135 , 0.71518937, 0.60276338])

In [56]:
b = np.random.sample((3,3))
b

array([[0.09834683, 0.42110763, 0.95788953],
       [0.53316528, 0.69187711, 0.31551563],
       [0.68650093, 0.83462567, 0.01828828]])

In [74]:
b = np.random.randint(1,10, (3,3))
b

array([[7, 9, 9],
       [2, 7, 8],
       [8, 9, 2]])

In [75]:
b[0,0]

7

In [77]:
b[:2, :2]

array([[7, 9],
       [2, 7]])

In [78]:
b[1:, 1:]

array([[7, 8],
       [9, 2]])

In [79]:
b

array([[7, 9, 9],
       [2, 7, 8],
       [8, 9, 2]])

In [80]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [81]:
b * b

array([[49, 81, 81],
       [ 4, 49, 64],
       [64, 81,  4]])

In [82]:
b + 2

array([[ 9, 11, 11],
       [ 4,  9, 10],
       [10, 11,  4]])

In [83]:
b - 2

array([[5, 7, 7],
       [0, 5, 6],
       [6, 7, 0]])

In [84]:
b * 2

array([[14, 18, 18],
       [ 4, 14, 16],
       [16, 18,  4]])

In [86]:
b ** 2

array([[49, 81, 81],
       [ 4, 49, 64],
       [64, 81,  4]], dtype=int32)

In [87]:
b / 2

array([[3.5, 4.5, 4.5],
       [1. , 3.5, 4. ],
       [4. , 4.5, 1. ]])

In [88]:
np.add(b,2)

array([[ 9, 11, 11],
       [ 4,  9, 10],
       [10, 11,  4]])

In [90]:
np.exp(b)

array([[1.09663316e+03, 8.10308393e+03, 8.10308393e+03],
       [7.38905610e+00, 1.09663316e+03, 2.98095799e+03],
       [2.98095799e+03, 8.10308393e+03, 7.38905610e+00]])

In [91]:
v = np.arange(1,10,2)
v

array([1, 3, 5, 7, 9])

In [92]:
v + 2

array([ 3,  5,  7,  9, 11])

In [93]:
v * 2

array([ 2,  6, 10, 14, 18])

In [94]:
v - 1

array([0, 2, 4, 6, 8])

In [95]:
v / 2

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [96]:
b

array([[7, 9, 9],
       [2, 7, 8],
       [8, 9, 2]])

In [98]:
m = np.matrix(b)
m

matrix([[7, 9, 9],
        [2, 7, 8],
        [8, 9, 2]])

In [99]:
type(m)

numpy.matrix

In [100]:
m.T

matrix([[7, 2, 8],
        [9, 7, 9],
        [9, 8, 2]])

In [101]:
m * m.T

matrix([[211, 149, 155],
        [149, 117,  95],
        [155,  95, 149]])

In [102]:
m + 2

matrix([[ 9, 11, 11],
        [ 4,  9, 10],
        [10, 11,  4]])

In [103]:
m - 2

matrix([[5, 7, 7],
        [0, 5, 6],
        [6, 7, 0]])

In [104]:
m // 2

matrix([[3, 4, 4],
        [1, 3, 4],
        [4, 4, 1]], dtype=int32)

In [106]:
m

matrix([[7, 9, 9],
        [2, 7, 8],
        [8, 9, 2]])

In [107]:
b.sum()

61

In [108]:
m.sum()

61

In [109]:
b.mean()

6.777777777777778

In [110]:
b.std()

2.657391276244755

In [111]:
b.var()

7.061728395061729

In [112]:
b

array([[7, 9, 9],
       [2, 7, 8],
       [8, 9, 2]])

In [113]:
b.sum(axis = 0) # Column

array([17, 25, 19])

In [114]:
b.sum(axis = 1) # Rows

array([25, 17, 19])

In [115]:
b.mean(axis = 0)

array([5.66666667, 8.33333333, 6.33333333])

In [ ]:
# Pandas

In [116]:
import pandas as pd

In [155]:
df = pd.read_csv(r'C:\Users\91965\Documents\BI\Tableau - Module\superstore_dataset2011-2015.csv')

In [119]:
df = pd.read_csv('C:/Users/91965/Documents/BI/Tableau - Module/superstore_dataset2011-2015.csv')

In [120]:
df.head()

Row ID         Order ID  Order Date    Sales  Quantity  Discount   Profit  \
0   48883     HU-2011-1220  01-01-2011   66.120         4       0.0   29.640   
1   11731  IT-2011-3647632  01-01-2011   44.865         3       0.5  -26.055   
2   42433     AG-2011-2040  01-01-2011  408.300         2       0.0  106.140   
3   22253    IN-2011-47883  01-01-2011  120.366         3       0.1   36.036   
4   22255    IN-2011-47883  01-01-2011  113.670         5       0.1   37.770   

   Shipping Cost Order Priority  
0           8.17           High  
1           4.82           High  
2          35.46         Medium  
3           9.72         Medium  
4           4.70         Medium

In [183]:
test = pd.read_csv('Test.csv')

In [184]:
test.head(1)

Unnamed: 0  Row ID      Order ID  Order Date  Sales  Quantity  Discount  \
0           0   48883  HU-2011-1220  01-01-2011  66.12         4       0.0   

   Profit  Shipping Cost Order Priority  
0   29.64           8.17           High

In [122]:
df1 = pd.read_excel(r'C:\Users\91965\Documents\BI\Tableau - Module\Tableau - Oct Batch\Chapter04\PropertyOrderProduct.xlsx', sheet_name = "Products")

In [123]:
df1.head()

ProductID  ProductName ProductCategory  Price
0          1  Large Towel    Housekeeping      9
1          2   Hand Towel    Housekeeping      5
2          3    Washcloth    Housekeeping      3
3          4      Shampoo    Housekeeping     40
4          5  Moisturizer    Housekeeping     40

In [124]:
df2 = df.iloc[:5,:]
df2

Row ID         Order ID  Order Date    Sales  Quantity  Discount   Profit  \
0   48883     HU-2011-1220  01-01-2011   66.120         4       0.0   29.640   
1   11731  IT-2011-3647632  01-01-2011   44.865         3       0.5  -26.055   
2   42433     AG-2011-2040  01-01-2011  408.300         2       0.0  106.140   
3   22253    IN-2011-47883  01-01-2011  120.366         3       0.1   36.036   
4   22255    IN-2011-47883  01-01-2011  113.670         5       0.1   37.770   

   Shipping Cost Order Priority  
0           8.17           High  
1           4.82           High  
2          35.46         Medium  
3           9.72         Medium  
4           4.70         Medium

In [125]:
df2.to_csv('Test.csv')

In [126]:
df2.to_excel('Test.xlsx')

In [127]:
type(df2)

pandas.core.frame.DataFrame

In [135]:
df = pd.DataFrame(np.random.randint(1,20,(10,4)))
df

0   1   2   3
0  15   4  18  19
1  15  10   2   5
2  11  12   9  12
3   3  17   1   1
4   7  15  11   9
5  14   3   4   3
6  12  14  17   9
7   9   9   3   4
8  13  15   1   5
9   4  14  12  14

In [136]:
df = pd.DataFrame(np.random.randint(1,20,(10,4)), columns = ['A', 'B', 'C', 'D'])
df

A   B   C   D
0  14  12  17  15
1  17   2   9   1
2   5   7  14   8
3  16  10  19   9
4  16  12   7  16
5   2  13   4  19
6  16   4  11  13
7   7   4   6  12
8   1  12   9  11
9  12   6  16   9

In [137]:
df = pd.DataFrame(np.random.randint(1,20,(10,4)), columns = list('ABCD'))
df

A   B   C   D
0  3  15   4   4
1  8  10  10  10
2  4  15  19  13
3  4  10  11  14
4  8   8   2  13
5  3   3   2   6
6  9   5   1  12
7  3   6  17   9
8  2  18  17   4
9  9   5  17   4

In [138]:
index_a = pd.date_range(start = "31-01-2021", periods = 10, freq = "D")
index_a

DatetimeIndex(['2021-01-31', '2021-02-01', '2021-02-02', '2021-02-03',
               '2021-02-04', '2021-02-05', '2021-02-06', '2021-02-07',
               '2021-02-08', '2021-02-09'],
              dtype='datetime64[ns]', freq='D')

In [175]:
df = pd.DataFrame(np.random.randint(1,20,(10,4)), index = index_a, columns = list('ABCD'))
df

A   B   C   D
2021-01-31   9   8  14  18
2021-02-01   1  12   5   1
2021-02-02  11  15  19   5
2021-02-03   4   8   9  14
2021-02-04   6   1   9  16
2021-02-05  16  12   5   8
2021-02-06  14  11  15  18
2021-02-07   4  10  19   3
2021-02-08  12  19  14   2
2021-02-09   7  11  17  17

In [143]:
df[:2]

A   B   C   D
2021-01-31  8   4  19  18
2021-02-01  2  19  18   3

In [144]:
df['C']

2021-01-31    19
2021-02-01    18
2021-02-02    13
2021-02-03     8
2021-02-04     7
2021-02-05    18
2021-02-06    19
2021-02-07    18
2021-02-08    11
2021-02-09    15
Freq: D, Name: C, dtype: int32

In [145]:
df.loc[:,['A', 'C']]

A   C
2021-01-31   8  19
2021-02-01   2  18
2021-02-02   6  13
2021-02-03   3   8
2021-02-04  12   7
2021-02-05  19  18
2021-02-06  15  19
2021-02-07  10  18
2021-02-08   1  11
2021-02-09   4  15

In [152]:
df.loc['2021-01-31':'2021-02-04','A':'C']

A   B   C
2021-01-31   8   4  19
2021-02-01   2  19  18
2021-02-02   6   6  13
2021-02-03   3  16   8
2021-02-04  12  18   7

In [153]:
df.iloc[:3, :2]

A   B
2021-01-31  8   4
2021-02-01  2  19
2021-02-02  6   6

In [154]:
df.iloc[:3, [1,3]]

B   D
2021-01-31   4  18
2021-02-01  19   3
2021-02-02   6  13

In [156]:
df

Row ID         Order ID  Order Date    Sales  Quantity  Discount  \
0    48883     HU-2011-1220  01-01-2011   66.120         4      0.00   
1    11731  IT-2011-3647632  01-01-2011   44.865         3      0.50   
2    42433     AG-2011-2040  01-01-2011  408.300         2      0.00   
3    22253    IN-2011-47883  01-01-2011  120.366         3      0.10   
4    22255    IN-2011-47883  01-01-2011  113.670         5      0.10   
5    22254    IN-2011-47883  01-01-2011   55.242         2      0.10   
6    21613    IN-2011-30733  01-02-2011  285.780         2      0.00   
7    44508     AO-2011-1390  01-02-2011  206.400         1      0.00   
8    23688    ID-2011-56493  01-02-2011  162.720         3      0.00   
9    21615    IN-2011-30733  01-02-2011   40.680         3      0.00   
10   21614    IN-2011-30733  01-02-2011   22.650         5      0.00   
11   21616    IN-2011-30733  01-02-2011   20.340         3      0.00   
12   34662   CA-2011-115161  01-02-2011  290.666         2      0.15   
13   41445     IR-2011-6550  01-02-2011  309.600         6      0.00   
14   16727  ES-2011-5268439  01-02-2011  139.650         5      0.00   
15   16726  ES-2011-5268439  01-02-2011   21.390         1      0.00   
16   25293    IN-2011-36074  01-02-2011  352.350         5      0.00   
17    8483   US-2011-118892  01-02-2011  400.704         2      0.40   
18    8484   US-2011-118892  01-02-2011   81.984         2      0.40   
19   19796  ES-2011-5460465  01-02-2011   78.300         3      0.00   

      Profit  Shipping Cost Order Priority  
0    29.6400           8.17           High  
1   -26.0550           4.82           High  
2   106.1400          35.46         Medium  
3    36.0360           9.72         Medium  
4    37.7700           4.70         Medium  
5    15.3420           1.80         Medium  
6    71.4000          57.30       Critical  
7    92.8800          53.08       Critical  
8    68.3100          44.36       Critical  
9    11.7900          11.13       Critical  
10    9.6000           5.29       Critical  
11    9.9000           3.78       Critical  
12    3.4196          54.64           High  
13  148.5000          19.65           High  
14   15.3000          19.23           High  
15    0.0000           3.34           High  
16  137.4000          33.15         Medium  
17   20.0240          21.38         Medium  
18  -19.1360           6.21         Medium  
19   20.3400           6.03         Medium

In [157]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [158]:
len(df.columns)

9

In [161]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [164]:
df.head(2)

Row ID         Order ID  Order Date   Sales  Quantity  Discount  Profit  \
0   48883     HU-2011-1220  01-01-2011  66.120         4       0.0  29.640   
1   11731  IT-2011-3647632  01-01-2011  44.865         3       0.5 -26.055   

   Shipping Cost Order Priority  
0           8.17           High  
1           4.82           High

In [165]:
df.tail(2)

Row ID         Order ID  Order Date   Sales  Quantity  Discount  Profit  \
18    8484   US-2011-118892  01-02-2011  81.984         2       0.4 -19.136   
19   19796  ES-2011-5460465  01-02-2011  78.300         3       0.0  20.340   

    Shipping Cost Order Priority  
18           6.21         Medium  
19           6.03         Medium

In [166]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_tslib

In [170]:
pd.value_counts(df['Order Priority'])

Medium      8
High        6
Critical    6
Name: Order Priority, dtype: int64

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
Row ID            20 non-null int64
Order ID          20 non-null object
Order Date        20 non-null object
Sales             20 non-null float64
Quantity          20 non-null int64
Discount          20 non-null float64
Profit            20 non-null float64
Shipping Cost     20 non-null float64
Order Priority    20 non-null object
dtypes: float64(4), int64(2), object(3)
memory usage: 1.5+ KB


In [173]:
df.describe()

Row ID       Sales   Quantity   Discount      Profit  \
count     20.000000   20.000000  20.000000  20.000000   20.000000   
mean   24803.950000  161.088850   3.100000   0.087500   39.430030   
std    11638.880202  132.933971   1.447321   0.157175   49.079329   
min     8483.000000   20.340000   1.000000   0.000000  -26.055000   
25%    19028.750000   52.647750   2.000000   0.000000    9.825000   
50%    21934.500000  117.018000   3.000000   0.000000   20.182000   
75%    27635.250000  287.001500   4.250000   0.100000   69.082500   
max    48883.000000  408.300000   6.000000   0.500000  148.500000   

       Shipping Cost  
count      20.000000  
mean       20.162000  
std        19.133003  
min         1.800000  
25%         5.172500  
50%        10.425000  
75%        33.727500  
max        57.300000

In [174]:
df.shape

(20, 9)

In [176]:
df

A   B   C   D
2021-01-31   9   8  14  18
2021-02-01   1  12   5   1
2021-02-02  11  15  19   5
2021-02-03   4   8   9  14
2021-02-04   6   1   9  16
2021-02-05  16  12   5   8
2021-02-06  14  11  15  18
2021-02-07   4  10  19   3
2021-02-08  12  19  14   2
2021-02-09   7  11  17  17

In [178]:
df.sort_index(ascending = False)

A   B   C   D
2021-02-09   7  11  17  17
2021-02-08  12  19  14   2
2021-02-07   4  10  19   3
2021-02-06  14  11  15  18
2021-02-05  16  12   5   8
2021-02-04   6   1   9  16
2021-02-03   4   8   9  14
2021-02-02  11  15  19   5
2021-02-01   1  12   5   1
2021-01-31   9   8  14  18

In [179]:
df.sort_index()

A   B   C   D
2021-01-31   9   8  14  18
2021-02-01   1  12   5   1
2021-02-02  11  15  19   5
2021-02-03   4   8   9  14
2021-02-04   6   1   9  16
2021-02-05  16  12   5   8
2021-02-06  14  11  15  18
2021-02-07   4  10  19   3
2021-02-08  12  19  14   2
2021-02-09   7  11  17  17

In [181]:
df.sort_values("A")

A   B   C   D
2021-02-01   1  12   5   1
2021-02-03   4   8   9  14
2021-02-07   4  10  19   3
2021-02-04   6   1   9  16
2021-02-09   7  11  17  17
2021-01-31   9   8  14  18
2021-02-02  11  15  19   5
2021-02-08  12  19  14   2
2021-02-06  14  11  15  18
2021-02-05  16  12   5   8

In [182]:
df.sort_values("A", ascending = False)

A   B   C   D
2021-02-05  16  12   5   8
2021-02-06  14  11  15  18
2021-02-08  12  19  14   2
2021-02-02  11  15  19   5
2021-01-31   9   8  14  18
2021-02-09   7  11  17  17
2021-02-04   6   1   9  16
2021-02-03   4   8   9  14
2021-02-07   4  10  19   3
2021-02-01   1  12   5   1